version: '3'

services:
    nginx:
        image: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/jackfruit.conf:/etc/nginx/conf.d/default.conf
            # spinach 前端專案
            - ./gitlab/spinach:/usr/share/nginx/html/frontend-admin-tpl
        links:
            - jackfruit
    swagger:
        image: swaggerapi/swagger-ui
        ports:
            - '8081:8080'
        volumes:
            - ./gitlab/mangosteen/storage:/usr/share/nginx/html/swagger
        environment:
            URLS: "[{ url: \"swagger/api-docs/test_1.json\", name: \"test_1\" },{url: \"swagger/api-docs/test_2.json\", name: \"test_2\"} ]"
    jackfruit:
        build: ./images/jackfruit/
        ports:
            - "9000:9000"
        volumes:
            # php.ini 設定
            - ./gitlab/jackfruit/container/php.ini:/usr/local/etc/php.ini
            # jackfruit後端專案
            - ./gitlab/jackfruit:/var/www/html
        tty: true
    nginx_mangosteen:
        image: nginx
        ports:
            - '8080:80'
        volumes:
            - ./nginx/mangosteen.conf:/etc/nginx/conf.d/default.conf
            # spinach 前端專案
            - ./gitlab/wysiwyg_editor:/usr/share/nginx/html/frontend-admin-tpl
        links:
            - mangosteen
    mangosteen:
        build: ./images/mangosteen/
        ports:
            - "9001:9000"
        volumes:
            # php.ini 設定
            - ./gitlab/mangosteen/container/php.ini:/usr/local/etc/php.ini
            # jackfruit後端專案
            - ./gitlab/mangosteen:/var/www/html
        tty: true

    #用來監控背景服務
    supervisor:
        build: ./images/jackfruit/
        volumes:
            # php.ini 設定
            - ./gitlab/jackfruit/container/php.ini:/usr/local/etc/php.ini
            # jackfruit後端專案
            - ./gitlab/jackfruit:/var/www/html
        command: su -c "php /var/www/html/artisan queue:work database --delay=3 --sleep=3 --tries=3 --daemon>> /dev/null 2>&1" -s /bin/bash www-data
        tty: true
    #用來查看gcp上 QA與正式站的資料庫
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOSTS=qa,prod,stagging
            - PMA_USER=backend
            - PMA_PASSWORD=fP2bea4q5GHY
        ports:
        - '8888:80'

    qa:
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: /cloud_sql_proxy -instances rd1-test-project:asia-east1:pineapple-db=tcp:0.0.0.0:3306
        volumes:
        - "${HOME}/.config/gcloud:/root/.config/gcloud"
    prod:
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: /cloud_sql_proxy -instances rd1-prod-project:asia-east1:pineapple-db=tcp:0.0.0.0:3306
        volumes:
        - "${HOME}/.config/gcloud:/root/.config/gcloud"
    stagging:
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: /cloud_sql_proxy -instances gcp-20190920-02:asia-east1:bbos-client:bbos-client=tcp:0.0.0.0:3306
        volumes:
        - "${HOME}/.config/gcloud:/root/.config/gcloud"

    #用來查看local的資料庫
    phpmyadmin_dev:
        image: phpmyadmin/phpmyadmin
        ports:
        - '8889:80'
        links:
            - db_dev:db_dev
        environment:
            PMA_HOST: db_dev
    db_dev:
        image: mysql:5.7.24
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: qwe123
        ports:
        - '3306:3306'
        volumes:
            - my-datavolume:/var/lib/mysql
volumes:
    my-datavolume: