version: '3'

services:
    twstock:
        build: ./
        ports:
            - "6090:80"
        volumes:
            - ./:/app/
        tty: true
    nginx:
        image: nginx
        ports:
            - '6080:80'
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/usr/share/nginx/html/twstock/public
        links:
            - twstock